FROM alterafpga/quartus-pro:25.3.1-patch1.02-agilex5

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      libegl1 \
      libfontconfig1 \
      libgl1 \
      libice6 \
      libsm6 \
      libx11-xcb1 \
      libxcb-cursor0 \
      libxcb-icccm4 \
      libxcb-image0 \
      libxcb-keysyms1 \
      libxcb-randr0 \
      libxcb-render-util0 \
      libxcb-shape0 \
      libxcb-shm0 \
      libxcb-sync1 \
      libxcb-xfixes0 \
      libxcb-xinerama0 \
      libxkbcommon-x11-0 \
 && rm -rf /var/lib/apt/lists/*

