// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-snes-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_snes_pll_profiles (
    input  logic        pal,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [31:0] c2_settings,
    output logic [31:0] c3_settings,
    output logic [31:0] c4_settings,
    output logic [14:0] charge_pump_settings
);
    logic [206:0] profile;

    always_comb begin
        case (pal)
        1'b0: profile = {32'h0BD20403, 32'h0580080B, 32'h0B312016, 32'h1600082C, 32'h0580580B, 32'h0580680B, 15'h0042};
        1'b1: profile = {32'h08F20202, 32'h0700080E, 32'h0E29701C, 32'h1C000838, 32'h0730680E, 32'h0710800E, 15'h0063};
            default: profile = '0;
        endcase
    end

    assign {m_settings, c0_settings, c1_settings, c2_settings,
            c3_settings, c4_settings, charge_pump_settings} = profile;
endmodule
