// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-nes-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_nes_pll_profiles (
    input  logic        pal,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [31:0] c2_settings,
    output logic [31:0] c3_settings,
    output logic [31:0] c4_settings,
    output logic [14:0] charge_pump_settings
);
    logic [206:0] profile;

    always_comb begin
        case (pal)
        1'b0: profile = {32'h0BD20403, 32'h0580080B, 32'h0B000816, 32'h1600082C, 32'h0580580B, 32'h0580B00B, 15'h0042};
        1'b1: profile = {32'h08F00402, 32'h8500080B, 32'h0A800815, 32'h1500082A, 32'h8528500B, 32'h8508A80B, 15'h0063};
            default: profile = '0;
        endcase
    end

    assign {m_settings, c0_settings, c1_settings, c2_settings,
            c3_settings, c4_settings, charge_pump_settings} = profile;
endmodule
