// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-minimig-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_minimig_pll_profiles (
    input  logic        ntsc,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [14:0] charge_pump_settings
);
    logic [110:0] profile;

    always_comb begin
        case (ntsc)
        1'b0: profile = {32'h0E300402, 32'h8600080D, 32'h19000832, 15'h0042};
        1'b1: profile = {32'h0B320202, 32'h0680080D, 32'h1A000834, 15'h0042};
            default: profile = '0;
        endcase
    end

    assign {m_settings, c0_settings, c1_settings,
            charge_pump_settings} = profile;
endmodule
