// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-sms-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_sms_pll_profiles (
    input  logic        pal,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [31:0] c2_settings,
    output logic [14:0] charge_pump_settings
);
    logic [142:0] profile;

    always_comb begin
        case (pal)
        1'b0: profile = {32'h0BD00402, 32'h0B000816, 32'h0B109016, 32'h0B000816, 15'h0042};
        1'b1: profile = {32'h0A620202, 32'h0D00081A, 32'h0D20A81A, 32'h0D00081A, 15'h0042};
            default: profile = '0;
        endcase
    end

    assign {m_settings, c0_settings, c1_settings, c2_settings,
            charge_pump_settings} = profile;
endmodule
