#!/usr/bin/env python3
"""Convert Quartus's exact-OPN IOPLL solutions into synthesizable profiles."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PROFILE_RE = re.compile(r"MEMTEST_PROFILE (?P<fields>.*)$")


def flag(value: str) -> int:
    return int(value.lower() == "true")


def byte_count(value: str) -> int:
    number = int(value)
    return 0 if number == 256 else number


def counter_word(profile: dict[str, str], prefix: str) -> int:
    high = byte_count(profile[f"{prefix}_hi"])
    low = byte_count(profile[f"{prefix}_lo"])
    return (
        (flag(profile[f"{prefix}_odd"]) << 31)
        | (low << 23)
        | (int(profile[f"{prefix}_phase"]) << 19)
        | (int(profile[f"{prefix}_preset"]) << 11)
        | (flag(profile[f"{prefix}_bypass"]) << 8)
        | high
    )


def charge_pump(multiply: int) -> int:
    ranges = (
        (2, 2, 0b00011, 0b10101, 0b11111),
        (3, 7, 0b00011, 0b10001, 0b11010),
        (8, 10, 0b00010, 0b10000, 0b11000),
        (11, 15, 0b00010, 0b01100, 0b10010),
        (16, 23, 0b00001, 0b01001, 0b01110),
        (24, 43, 0b00000, 0b01000, 0b01100),
        (44, 64, 0b00000, 0b00110, 0b01001),
        (65, 85, 0b00000, 0b00110, 0b00110),
        (86, 124, 0b00000, 0b00101, 0b00101),
        (125, 160, 0b00000, 0b00011, 0b00011),
        (161, 320, 0b00000, 0b00010, 0b00010),
    )
    for minimum, maximum, high, middle, low in ranges:
        if minimum <= multiply <= maximum:
            return (high << 10) | (middle << 5) | low
    raise ValueError(f"multiply factor {multiply} has no charge-pump profile")


def parse_profiles(path: Path) -> list[dict[str, str]]:
    profiles = []
    for line in path.read_text().splitlines():
        match = PROFILE_RE.search(line)
        if not match or "Info: Info:" not in line:
            continue
        fields = dict(item.split("=", 1) for item in match.group("fields").split())
        profiles.append(fields)
    if len(profiles) != 64:
        raise ValueError(f"expected 64 profiles, found {len(profiles)}")
    return profiles


def render(profiles: list[dict[str, str]]) -> str:
    case_lines = []
    for index, profile in enumerate(profiles):
        requested = profile["requested"]
        actual = profile["actual"]
        if abs(float(requested) - float(actual)) > 0.0001:
            raise ValueError(f"Quartus approximated {requested} MHz as {actual} MHz")
        actual1 = profile["actual1"]
        if abs(float(requested) - float(actual1)) > 0.0001:
            raise ValueError(
                f"Quartus approximated C1 {requested} MHz as {actual1} MHz"
            )
        expected_phase = 500.0 / float(requested) - 0.5
        actual_phase = float(profile["phase1"]) / 1000.0
        # The IOPLL quantizes arbitrary phases to VCO phase steps. The packed
        # counter word below preserves Quartus's exact legal solution.
        if abs(expected_phase - actual_phase) > 0.2:
            raise ValueError(
                f"Quartus C1 phase {actual_phase} ns differs from "
                f"SDRAM capture target {expected_phase} ns"
            )

        m = int(profile["m"])
        n_hi = byte_count(profile["n_hi"])
        n_lo = byte_count(profile["n_lo"])
        m_word = (
            (m << 20)
            | (flag(profile["n_odd"]) << 17)
            | (n_lo << 9)
            | (flag(profile["n_bypass"]) << 8)
            | n_hi
        )

        c0_word = counter_word(profile, "c0")
        c1_word = counter_word(profile, "c1")
        # MemTest's vgaout treats the three low nibbles as decimal glyphs.
        # Keep the legacy display convention: 167 MHz -> 12'h167 and
        # 62.5 MHz -> 12'h625.
        digits = requested.replace(".", "")
        if not digits.isdigit() or len(digits) > 3:
            raise ValueError(f"cannot encode {requested} MHz for MemTest display")
        frequency_bcd = int(digits.zfill(3), 16)
        cp_word = charge_pump(m)
        case_lines.append(
            f"            6'd{index}: profile = "
            f"{{12'h{frequency_bcd:03X}, 32'h{m_word:08X}, "
            f"32'h{c0_word:08X}, 32'h{c1_word:08X}, 15'h{cp_word:04X}}};"
        )

    cases = "\n".join(case_lines)
    return f'''// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-memtest-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_memtest_pll_profiles (
    input  logic  [5:0] index,
    output logic [11:0] frequency_bcd,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [14:0] charge_pump_settings
);
    logic [122:0] profile;

    always_comb begin
        case (index)
{cases}
            default: profile = {{12'h045, 32'd0, 32'd0, 32'd0, 15'd0}};
        endcase
    end

    assign {{frequency_bcd, m_settings, c0_settings, c1_settings,
            charge_pump_settings}} = profile;
endmodule
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render(parse_profiles(args.input)))


if __name__ == "__main__":
    main()
