#!/usr/bin/env python3
"""Convert exact-device Quartus SNES IOPLL solutions into HDL profiles."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PROFILE_RE = re.compile(r"SNES_PROFILE (?P<fields>.*)$")
EXPECTED_REQUESTS = {
    "ntsc": (85.9090800, 42.9545400, 21.4772700),
    "pal": (85.1254784, 42.5627392, 21.2813696),
}


def flag(value: str) -> int:
    return int(value.lower() == "true" or value == "1")


def byte_count(value: str) -> int:
    number = int(value)
    return 0 if number == 256 else number


def counter_word(profile: dict[str, str], index: int) -> int:
    high = byte_count(profile[f"hi{index}"])
    low = byte_count(profile[f"lo{index}"])
    return (
        (flag(profile[f"odd{index}"]) << 31)
        | (low << 23)
        | (int(profile[f"phase{index}"]) << 19)
        | (int(profile[f"preset{index}"]) << 11)
        | (flag(profile[f"bypass{index}"]) << 8)
        | high
    )


def charge_pump(multiply: int) -> int:
    ranges = (
        (2, 2, 0b00011, 0b10101, 0b11111),
        (3, 7, 0b00011, 0b10001, 0b11010),
        (8, 10, 0b00010, 0b10000, 0b11000),
        (11, 15, 0b00010, 0b01100, 0b10010),
        (16, 23, 0b00001, 0b01001, 0b01110),
        (24, 43, 0b00000, 0b01000, 0b01100),
        (44, 64, 0b00000, 0b00110, 0b01001),
        (65, 85, 0b00000, 0b00110, 0b00110),
        (86, 124, 0b00000, 0b00101, 0b00101),
        (125, 160, 0b00000, 0b00011, 0b00011),
        (161, 320, 0b00000, 0b00010, 0b00010),
    )
    for minimum, maximum, high, middle, low in ranges:
        if minimum <= multiply <= maximum:
            return (high << 10) | (middle << 5) | low
    raise ValueError(f"multiply factor {multiply} has no charge-pump profile")


def parse_profiles(path: Path) -> dict[str, dict[str, str]]:
    profiles = {}
    for line in path.read_text().splitlines():
        match = PROFILE_RE.search(line)
        if not match or "Info: Info:" not in line:
            continue
        fields = dict(item.split("=", 1) for item in match.group("fields").split())
        profiles[fields["profile"]] = fields
    if set(profiles) != set(EXPECTED_REQUESTS):
        raise ValueError(f"expected {sorted(EXPECTED_REQUESTS)}, found {sorted(profiles)}")
    return profiles


def validate(profile: dict[str, str]) -> None:
    name = profile["profile"]
    for index, expected in enumerate(EXPECTED_REQUESTS[name]):
        requested = float(profile[f"requested{index}"])
        actual = float(profile[f"actual{index}"])
        if abs(requested - expected) > 1e-7:
            raise ValueError(f"{name} C{index} request changed")
        if abs(actual - expected) / expected > 0.0001:
            raise ValueError(f"{name} C{index} error is greater than 0.01%")

    for index in (1, 3, 4):
        requested = float(profile[f"phase_requested{index}"])
        actual = float(profile[f"actual_phase{index}"])
        if abs(actual - requested) > 100.0:
            raise ValueError(f"{name} C{index} phase error is greater than 0.1 ns")


def profile_words(profile: dict[str, str]) -> tuple[int, list[int], int]:
    multiply = int(profile["m"])
    n_high = byte_count(profile["n_hi"])
    n_low = byte_count(profile["n_lo"])
    m_word = (
        (multiply << 20)
        | (flag(profile["n_odd"]) << 17)
        | (n_low << 9)
        | (flag(profile["n_bypass"]) << 8)
        | n_high
    )
    counters = [counter_word(profile, index) for index in range(5)]
    return m_word, counters, charge_pump(multiply)


def render(profiles: dict[str, dict[str, str]]) -> str:
    cases = []
    for name, select in (("ntsc", "1'b0"), ("pal", "1'b1")):
        profile = profiles[name]
        validate(profile)
        m_word, counters, cp_word = profile_words(profile)
        values = ", ".join(f"32'h{word:08X}" for word in [m_word, *counters])
        cases.append(
            f"        {select}: profile = {{{values}, 15'h{cp_word:04X}}};"
        )
    case_text = "\n".join(cases)
    return f'''// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-snes-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_snes_pll_profiles (
    input  logic        pal,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [31:0] c2_settings,
    output logic [31:0] c3_settings,
    output logic [31:0] c4_settings,
    output logic [14:0] charge_pump_settings
);
    logic [206:0] profile;

    always_comb begin
        case (pal)
{case_text}
            default: profile = '0;
        endcase
    end

    assign {{m_settings, c0_settings, c1_settings, c2_settings,
            c3_settings, c4_settings, charge_pump_settings}} = profile;
endmodule
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render(parse_profiles(args.input)))


if __name__ == "__main__":
    main()
