#!/usr/bin/env python3
"""Convert exact-device Quartus ao486 IOPLL solutions into HDL profiles."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PROFILE_RE = re.compile(r"AO486_PROFILE (?P<fields>.*)$")
CPU_FREQUENCIES = (90.0, 15.0, 30.0, 56.25, 100.0)


def flag(value: str) -> int:
    return int(value.lower() == "true" or value == "1")


def byte_count(value: str) -> int:
    number = int(value)
    return 0 if number == 256 else number


def counter_word(profile: dict[str, str], index: int) -> int:
    return (
        (flag(profile[f"odd{index}"]) << 31)
        | (byte_count(profile[f"lo{index}"]) << 23)
        | (int(profile[f"phase{index}"]) << 19)
        | (int(profile[f"preset{index}"]) << 11)
        | (flag(profile[f"bypass{index}"]) << 8)
        | byte_count(profile[f"hi{index}"])
    )


def charge_pump(multiply: int) -> int:
    ranges = (
        (2, 2, 0b00011, 0b10101, 0b11111),
        (3, 7, 0b00011, 0b10001, 0b11010),
        (8, 10, 0b00010, 0b10000, 0b11000),
        (11, 15, 0b00010, 0b01100, 0b10010),
        (16, 23, 0b00001, 0b01001, 0b01110),
        (24, 43, 0b00000, 0b01000, 0b01100),
        (44, 64, 0b00000, 0b00110, 0b01001),
        (65, 85, 0b00000, 0b00110, 0b00110),
        (86, 124, 0b00000, 0b00101, 0b00101),
        (125, 160, 0b00000, 0b00011, 0b00011),
        (161, 320, 0b00000, 0b00010, 0b00010),
    )
    for minimum, maximum, high, middle, low in ranges:
        if minimum <= multiply <= maximum:
            return (high << 10) | (middle << 5) | low
    raise ValueError(f"multiply factor {multiply} has no charge-pump profile")


def parse_profiles(path: Path) -> dict[str, dict[str, str]]:
    profiles = {}
    for line in path.read_text().splitlines():
        match = PROFILE_RE.search(line)
        if not match or "Info: Info:" not in line:
            continue
        fields = dict(item.split("=", 1) for item in match.group("fields").split())
        profiles[fields["profile"]] = fields
    expected = {f"s{speed}" for speed in range(5)}
    if set(profiles) != expected:
        raise ValueError(f"expected {sorted(expected)}, found {sorted(profiles)}")
    return profiles


def profile_words(profile: dict[str, str]) -> tuple[int, int, int, int]:
    m = int(profile["m"])
    m_word = (
        (m << 20)
        | (flag(profile["n_odd"]) << 17)
        | (byte_count(profile["n_lo"]) << 9)
        | (flag(profile["n_bypass"]) << 8)
        | byte_count(profile["n_hi"])
    )
    return (
        m_word,
        counter_word(profile, 0),
        counter_word(profile, 1),
        charge_pump(m),
    )


def validate(profile: dict[str, str], speed: int) -> None:
    expected = CPU_FREQUENCIES[speed]
    actual = float(profile["actual0"])
    if abs(actual - expected) / expected > 0.0002:
        raise ValueError(
            f"{profile['profile']} C0 error is greater than 0.02%: "
            f"requested {expected}, got {actual}"
        )
    physical = float(profile["actual1"])
    if abs(physical - expected) / expected > 0.0002:
        raise ValueError(
            f"{profile['profile']} C1 error is greater than 0.02%: "
            f"requested {expected}, got {physical}"
        )


def render(profiles: dict[str, dict[str, str]]) -> str:
    cases = []
    for speed in range(5):
        name = f"s{speed}"
        profile = profiles[name]
        validate(profile, speed)
        m_word, c0_word, c1_word, cp_word = profile_words(profile)
        cases.append(
            f"        3'd{speed}: profile = "
            f"{{32'h{m_word:08X}, 32'h{c0_word:08X}, "
            f"32'h{c1_word:08X}, 15'h{cp_word:04X}}};"
        )
    cases_text = "\n".join(cases)
    return f'''// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate-ao486-pll-profiles.py from Quartus 25.3.1
// solutions for A5EB013BB23BE4SCS. Do not hand-edit counter values.
module de25_ao486_pll_profiles (
    input  logic [2:0] speed,
    output logic [31:0] m_settings,
    output logic [31:0] c0_settings,
    output logic [31:0] c1_settings,
    output logic [14:0] charge_pump_settings
);
    logic [110:0] profile;
    logic [2:0] bounded_speed;

    assign bounded_speed = speed > 3'd4 ? 3'd4 : speed;
    always_comb begin
        case (bounded_speed)
{cases_text}
            default: profile = '0;
        endcase
    end

    assign {{m_settings, c0_settings, c1_settings,
            charge_pump_settings}} = profile;
endmodule
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render(parse_profiles(args.input)))


if __name__ == "__main__":
    main()
